### ISSUE TITLE
Feature: User can view landing page, see upcoming events, create new event.

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a landing page, see upcoming events, create new event

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

This is the landing page for when the user log in (log in feature comes later), users can navigate to upcoming events, create new events, search for events and interact with notification.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/36710918/209851228-5880e6d7-ff63-4a25-a95b-2e1af6651e79.png)
![image](https://user-images.githubusercontent.com/36710918/209851755-a7793cb2-88c5-41e4-9f89-417d09e76e3c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create a new user for testing purpose
- [x] Create new events to test display

### ☁️ Server Tasks

- [x] Within `server/index.js`, add GET listener that listen to '/home/userId={userId}' route
- [x] Within GET listener, db.query for events for the current `userId`
- [x] Then* set status 200 and send json response back to front end
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display home/landing page
- [x] Create a component to send `Fetch` (GET method) request to server for the upcoming events with the `userId`
- [x] On promise return, extract `result.rows` for `eventId, sport, date, time, eventName, createdAt` and update state
- [x] Create accordion component for the upcoming event table
- [x] Create navbar component with `anchor` element for title that has hashroute back to `/home`
- [x] Render jsx elements

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
