### ISSUE TITLE
Feature: User can view and edit their profile

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit their profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/36710918/209856323-e1932689-47f9-482b-b890-0b8bebd14ffc.png)
![image](https://user-images.githubusercontent.com/36710918/209856363-795180ec-9123-4cd0-9ca4-5912e2ab6bf4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to listen to `GET` request for the account info, extract `userId` from `req.params.userId`
- [x] Set up `sql.query` for user information where userId matches
- [x] Set res.status and send res.json of info back to frontend
- [x] Set up another listen to `PUT` request, extract userId and new info from `req.params` and `req.body`
- [x] Set up sql.query to `update` user info in `users` tables `where "userId"` matches
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new accountPage component that render account info when hashroute is '#account'
- [x] Within `componentDidMount` make a fetch `GET` request of path `/api/account/${userId}`
- [x] Store user account information within the `state`
- [x] Render the account information from `state`
- [x] Set initial state for `edit` to `false`
- [x] Within the render function, set up condition that check the state of `edit`, render form input and defaultValue when `state.edit === true`
- [x] When `state.edit === false`
- [x] Add edit `button` at the top
- [x] Add eventListener for edit button with callback function
- [x] When callback function is called, change the `state.edit: true`
- [x] When inside edit, add 2 more button at the bottom for saving the edit or cancel the edit
- [x] Add eventlistener to save button `onclick` event
- [x] Set up Fetch `PUT` method, extract new info from form elements
- [x] Send request to path `/api/account/edit/${userId}`
- [x] Attached new info to request body with `JSON.stringify(payload)`
- [x] On fetch fulfilled, set the new user info into state and reset state.edit to false

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
