### ISSUE TITLE
Feature: User can create new meet up

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create new meet up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon logged in, on home page, user can click on create event button to start creating a new event. User will need to fill out event information. Within the location input, user will get autofill with Google Maps API. Upon selecting the address, the corresponding map will update with a pointer to the address selected. When user click on creating event, they will be redirected to the newly created event page with all the information (previously filled) present including interactive Google Maps and link to get direction (straight from Google Maps website).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/36710918/209854130-dd77810f-e4e4-4671-8b70-c528f8f69948.png)
![image](https://user-images.githubusercontent.com/36710918/209853972-b2b6986c-1d8e-410c-b00e-7c125aa9f79a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to  listen to `POST` with path `/api/createEvent/{userId}`
- [x] Parse upcoming request for data within `req.body` to const sql
- [x] Create a sql command to `insert` new events into `events`, `locations` & `eventLocations` table
- [x] db.query with sql and params to the database
- [x] catch all errors
- [x] Update `server/index.js` to  listen to `POST` with path `/api/events/{eventId}`
- [x] Parse upcoming request for data within `req.body` to const sql
- [x] Create a sql command to `select` event where `eventId` is `req.params.eventId`
- [x] db.query with sql and params to the database
- [x] `res.status(200)` and `.json()` back the payload to frontend
- [x] catch all errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a "create event" page component
- [x] Import Google Maps API
- [x] Create a form control element
- [x] Create input elements
- [x] For location input, add onChange listener that link to Google maps API
- [x] Update the map once the location is set
- [x] On submit form => send Fetch POST request to back end with values from input elements
- [x] On respond, get the eventId
- [x] On success => redirect user to `#eventPage` with `props.event={eventId}`
- [x] Create an "event" page component
- [x] Use the eventId and send Fetch POST method to request the event information
- [x] Use Google Map API to request the google maps from the location from database
- [x] Include anchor link to open a new browser window link to google maps and address searched
- [x] Within `.env` file, add google api key
- [x] Update component button element on userLandingPage to link to create event page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
