### ISSUE TITLE
Feature: User can search for meet up within an area

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for meet up within an area

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On userLandingPage, user can click on search button and a drop down (accordion like) form will show up where user can filter their search. Upon search, it will take user to a "search" page where the result will show up. It will contain live google maps with event locations pinned and a table where user can get more information about the event. User can click on the event and it will take user to that event page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/36710918/209854272-037b73ef-50b8-47aa-b588-69f008272adb.png)
![image](https://user-images.githubusercontent.com/36710918/209854323-538c0240-d3fe-4d3f-8619-4ed31efb1e68.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to listen to 'POST' request for path '/search/{query...}'
- [x] Extract params from path
- [x] Set up SQL with event params
- [x] `select "eventName", "sport", "date", "time", "location", "lat", "lng", "participant", "note"`
- [x] `from "events"`
- [x] `join "eventLocations" with "locationId"`
- [x] `join "locations" with "locationId"`
- [x] `where "sport" = params, "lat" = ..., "lng" = ...`
- [x] Figure out how radius value will translate to "lat" / "lng"
- [x] Figure out the correct aggregate function to properly filter "lat/lng"
- [x] db.query
- [x] set status (200) and json() back the information
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update userLandingPage component search button to switch display attribute between '' and 'none'
- [x] Create a drop down (accordion like) form under the search event button
- [x] Within the form, add 3 inputs: sport [select element], area code (zip code)[text input], area size [select element]
- [x] Add event listener for the search button
- [x] Collect the values from form controlled elements
- [x] Update location hash to "search"
- [x] Call on new searchPage component and pass through form values as props
- [x] Create a component searchPage
- [x] Create `state = { result: null }` for storing future data
- [x] Parse values from props
- [x] Call on `<GmapsSetUp /> `and pass in zip code as props and get "lat"/"lng" as return for the current area center
- [x] Update `<GmapsSetup />` to parse for zip code props and use google maps geocoding api to get "lat"/"lng" with given zip code as input
- [x] On componentDidMount() -> create a fetch request with 'POST', headers, and body of values from props
- [x] On fetch return, extract result.rows to get the information from backend
- [x] Update the state to store the result data
- [x] On `render()` create a page that contain google maps and an accordion-like table of data
- [x] Extract state.data.lat and state.data.lng into array to pass to google maps component as props
- [x] For google maps, call on `<GmapsSetUp />` and pass in lat/lng array
- [x] For table, create an accordion component to render result into table-look-alike format
- [x] Use `.map` method to format information within the accordion
- [x] Each event on table will have a link that can take user to event page with href=`events?eventId={state.data.eventId}`
- [x] Each item will get an index that will match the index presented on the pins on google maps
- [x] Update `<GmapsSetUp />` component to look for certain incoming props
- [x] Update the google maps to put pins where the lat/lng array is given
- [x] Create a custom pins that includes index

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
