### ISSUE TITLE
Feature: User can edit the meet up

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit the meet up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can visit an event page and if the event is made by that user, there will be an edit button so that the user can edit the event that they created. Once edit button is clicked, it will take user back to create event page look-alike but with information already prefilled. User can then edit and save the new event information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/36710918/209854831-eb0a1d84-a799-40bb-a941-dc2b10344e32.png)
![image](https://user-images.githubusercontent.com/36710918/209854860-42269523-b886-4ef2-aed8-181f17089755.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to listen to request of `/api/event/edit/${eventId}`
- [x] Extract data from `req.body` and `req.params`
- [x] Set up a `db.query` using `update` and condition of `eventId`
- [x] Update `res.status` and `.json()`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create event component to check against Fetch request of the event for its `userId` to check against `AppContext` `userId`
- [x] If the `userId` matches then render the event page to include edit `button`
- [x] Add eventListener to the edit `button`
- [x] Redirect user to `edit` page component and sending event informations as props
- [x] Render the edit page component with similar design to create event page
- [x] Prefill inputs with props
- [x] Add a save `button` with eventlistener
- [x] Add a cancel `button` with eventlistener
- [x] On save button, preventDefault(), pull new inputs from `form` element and create a fetch request to update the event
- [x] On cancel, redirect user back to the same event page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
