### ISSUE TITLE
Feature: User can delete the meet up

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete the meet up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the owner of the event is editing the event, they will have an option to delete the event, when clicked on delete button, a modal will show up to ask the user to either confirm or cancel. When confirmed, user will be taken back to the home page, if cancel the modal will disappear and user can keep editing.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/36710918/209854937-5e4e536c-d188-4186-b331-17dc5c61b19f.png)
![image](https://user-images.githubusercontent.com/36710918/209855098-ee2497f7-8ac2-4411-ab52-52210792d059.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to listen for Fetch request `POST` at path `/api/event/delete/${eventId}`
- [x] Extract `eventId` from `req.params.eventId`
- [x] Create sql query for deleting event from `events` and `locations` and `eventLocations` tables 
- [x] Set res.status and res.json to confirm deletion back to front end
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update edit page component to include a delete button
- [x] Add an event listener to the delete button
- [x] Create a modal with a `text` element and two `button` elements
- [x] Add event listener to the confirm `button`
- [x] Add callback function for confirm event listener, within the function extract the eventId, send a fetch request to the backend at path `/api/event/delete/${eventId}`
- [x] Add event listener for cancel `button`
- [x] Add callback function for cancel that switch the modal off

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
