### ISSUE TITLE
Feature: User can log in/create profile

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log in/create profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user first visit the site, they will land at the landing page where they're greeted and have option to sign in or sign up, user can click the button which will take to either log in or create account page. Upon filling out the fields (username and password) user can log in or get error message if they input incorrect information. Upon completing new account form they'll be redirected back to sign in page and able to log in. When users log in successfully, they'll be redirected to '#home' page where they'll see their upcoming events.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/36710918/209855763-2cf6823d-ee4d-4c5d-8a26-c467e2f09d48.png)
![image](https://user-images.githubusercontent.com/36710918/209855795-c345aa31-1e0e-4dc5-9a3a-d03722c0e281.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

no tasks

### ☁️ Server Tasks

- [x] require argon2 and jwt
- [x] Update `server/index.js` to listen for POST request and route `/api/auth/sign-up` for signing up request
- [x] extract the req.body for the username and password
- [x] set up error response if username or password is missing
- [x] use argon2 to create a hashedPassword
- [x] within the argon promise, create a query to database
- [x] within the query promise, upon response received parse the `result.rows` and send back to front end
- [x] set up `CATCH` for any error and pass it to `errorMiddleware`
- [x] within `server/index.js` add another POST listener and route `/api/auth/sign-in` for signing in request
- [x] extract the req.body for the username and password
- [x] set up error response if username or password is missing
- [x] create a query to database for the username and hashedPassword
- [x] using verify method of argon2, check if hashedPassword matches password
- [x] if not matching, throw error to client
- [x] if matched, within the argon2.verify promise, create a new jsonwebtoken with payload and secret token key from .env
- [x] send created token and payload back to front end
- [x] set up `CATCH` for any error and pass it to `errorMiddleware`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for landing page with route "#" or ""
- [x] Add button that take user to log in page or sign up page
- [x] Create a component for sign in page and add a form control with 2 input boxes (username & password), log in button and an anchor to sign up page
- [x] Add eventlistener for sign in button
- [x] Set up a fetch (POST method) function to send request to `/api/auth/sign-in`
- [x] Set up request headers and body (with username and password) as required
- [x] Within the fetch promise, wait for the response, assign returned payload and token to `window.localStorage` with `setItem('react-context-jwt', token)` and redirect to `#home` hash route
- [x] Create another component for sign up page, add a form control for inputs
- [x] Add validation for password (minimum 8 characters, and at least 1 number)
- [x] Add eventlistener for register button
- [x] Set up a fetch (POST method) function to send request to `/api/auth/sign-up`
- [x] Set up request headers and body (with username and password) as required
- [x] Within fetch promise, when request is returned successfully, set up a timer pop-up message letting user know that they successfully created an account then hash route back to sign-in page
- [x] Update app.jsx component `this.state.user` to initialize with `null` and will get updated when user signs in
- [x] Update Navbar to show sign in initially and show account/sign out when they are signed in

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
